# https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
# Matrix - you can run the same job with different configurations, on different runners
# or on different node versions or gradle versions, etc.
# You do that by adding the strategy field to the job.
#
# By default, when one job fails - all other combinations are skipped.
#   - To avoid this default behavior add continue-on-error: true on job level.
#
#
#

name: 10 - Matrix Strategies
on:
  push:
    branches:
      - main
jobs:
  build: # this job will run for all the combinations of gradle_versions and os array (12 combinations in this case)
    continue-on-error: true
    strategy:
      # runs this build job multiple times once per value in the {{ matrix.os }}
      # all those jobs will run in parallel
      matrix:
        # can be any name
        gradle_versions: [ 7.4.2, 7.4.1, 7.4, 6.9.2 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ matrix.gradle_versions }}
      - name: Execute build
        run: ./gradlew build