# Re-using jobs/steps in multiple workflows.
#
# Eg:- Using one workflow inside job of other workflow
#

name: 11 - Reusable workflow
on:
  workflow_call: # can be called from other workflow
    inputs: # if some input needs to be provided from other workflow (like a function call)
      # not reserved, can be anything
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        default: Jar
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print artifact name
        run: echo ${{ inputs.artifact-name }}
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: $ {{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output info
        run: echo "Deploying..."