name: 12 - Using re-usable workflow
on:
  push:
    branches:
      - main
jobs:
  deploy:
    uses: ./.github/workflows/11_Reusable_Workflow_1.yml
    # Provide input values for the re-usable workflow
    with:
      artifact-name: Jar
#    secrets:
#      some-secret: ${{ secrets.some-secret }}