name: 5 - Job Artifacts and Outputs
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v3
      - name: Setup gradle on runner
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.2
      - name: Run tests
        run: ./gradlew test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      # An output is a simple value, not a file,
      # that's produced by a job and accessed by another job
      # not reserved, any name

      # Adding expression - {{  }}
      # Here, we want to access steps context value, defined below
      # https://docs.github.com/en/actions/learn-github-actions/contexts
      jar-file: ${{ steps.publish.outputs.jar-file }}
    steps:
      - name: Download code
        uses: actions/checkout@v3
      - name: Setup gradle on runner
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.2
      - name: Build
        run: ./gradlew build
      - name: Publish jar file name, so that other job can just use the file name, not content of file
        id: publish # Giving step a unique id
        run: find build/libs/*.jar -type f -execdir echo 'jar-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifacts # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: Jar # artifact name used for downloading
          path: build/libs/*.jar
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Jar artifacts # https://github.com/actions/download-artifact
        uses: actions/download-artifact@v3
        with:
          name: Jar
      - name: Show contents on ubuntu runner
        run: ls
      - name: Output filename
        # https://docs.github.com/en/actions/learn-github-actions/contexts#needs-context
        run: echo "${{ needs.build.outputs.jar-file }}"
      - name: Deploy
        run: echo "Deploying..."