# Environment Variables - https://docs.github.com/en/actions/learn-github-actions/variables
#   - variables provide a way to store and reuse non-sensitive configuration information.
#   - any configuration data such as compiler flags, usernames, or server names as variables.
# Default environment variables - https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables

# Secrets
#   - allows you to store secrets, eg: credentials etc..
#   - repo -> settings -> secrets
name: 7 - Environment variables and secrets
on:
  push:
    branches:
#      - main
      - dev
env: # Custom env variable for workflow level, unless job overrides it
  DB_NAME: demo
jobs:
  job1:
    environment: test # the test environment created in settings
    env: # At Job level
      NAME: test
      DB_NAME: demo2
      PORT: 8080
      PASSWORD: $ {{ secrets.TEST_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: Print env variable
        run: |
          echo "$DB_NAME"
          echo "$NAME"
          echo "$PORT"
      - name: Print secrets
        run: |
          echo "Printing secret"
          echo "Password: ${{ secrets.TEST_PASSWORD }}"
      - name: Print environment value
        run: echo "Token - ${{ secrets.TOKEN }}"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print repository secret
        run: echo "Token - ${{ secrets.TOKEN }}"