# Environment Variables - https://docs.github.com/en/actions/learn-github-actions/variables
#   - variables provide a way to store and reuse non-sensitive configuration information.
#   - any configuration data such as compiler flags, usernames, or server names as variables.
# Default environment variables - https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables

name: 7 - Environment variables and secrets
on:
  push:
    branches:
      - main
env: # Custom env variable for workflow level, unless job overrides it
  DB_NAME: demo
jobs:
  test:
    env: # At Job level
      NAME: test
      DB_NAME: demo2
      PORT: 8080
    runs-on: ubuntu-latest
    steps:
      - name: Print env variable
        run: |
          echo "$DB_NAME"
          echo "$NAME"
          echo "$PORT"
      - name: Testing
        run: echo "Testing..."
