name: 8 - Gradle caching

# Actions for gradle project - includes caching
# https://tomgregory.com/build-gradle-projects-with-github-actions/
# https://www.youtube.com/watch?v=a7T2MU2l-es
# https://github.com/tkgregory/gradle-github-actions-example/blob/master/.github/workflows/gradle.yml

on:
  push:
    branches:
      - main
jobs:
  build-without-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: build-without-cache
        run: ./gradlew build --no-daemon
  test-with-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - name: test-with-cache
        run: ./gradlew test --no-daemon
  build-with-cache:
    needs: test-with-cache
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - name: build-with-cache
        run: ./gradlew build --no-daemon
  build-with-gradle-build-action-cache:
    needs: build-with-cache
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - name: build-with-gradle-build-action-cache
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build