# If something goes wrong, current job gets cancelled, its subsequent steps and all
# other jobs are not executed in the workflow.
# This is the default behaviour.

# Sometimes we need to control the flow manually

# - Running jobs and steps conditionally
#  - Running jobs with a matrix
#  - Re-using workflows

# Controlling execution via if
#   Special condition function
#     - failure() -> returns true when prev step or job failed
#     - success() -> returns true when none of the prev steps have failed
#     - always() -> always returns true, causes the step to always execute, even when cancelled
#     - cancelled() -> returns true if the workflow has been cancelled
#   These functions can be used in conditions to ensure that certain steps only run,
#   when other step fail, succeeded, always run or cancelled.

name: 9 - Controlling workflow and job execution
on:
  push:
    branches:
      - main
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - uses: gradle/gradle-build-action@v2
      - name: Run tests
        id: test_id
        run: ./gradlew test
        # Run below step, only if above step fails
      - name: Upload test report
        # for if field, no need to use expression syntax
        # failure() should be used to override default git-hub action behavior
        # By adding failure(), github action knows, below step still needs to be evaluated,
        # if we have failing steps or jobs before that step.
        if: failure() && steps.test_id.outcome == 'failure'
        run: echo "Uploading test report"
  build-job:
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - uses: gradle/gradle-build-action@v2
      - name: Execute build
        run: ./gradlew build
  conditional-job:
    needs: test-job
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Print job info
        run: |
          echo "I am conditional job"
          echo ${{ toJSON(github) }}