# If something goes wrong, current job gets cancelled, its subsequent steps and all
# other jobs are not executed in the workflow.
# This is the default behaviour.

# Sometimes we need to control the flow manually

# - Running jobs and steps conditionally
#  - Running jobs with a matrix
#  - Re-using workflows

name: 9 - Controlling workflow and job execution
on:
  push:
    branches:
      - main
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - uses: gradle/gradle-build-action@v2
      - name: Run tests
        run: ./gradlew test
      - name: Upload test report
        run: echo "Uploading test report"
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - uses: gradle/gradle-build-action@v2
      - name: Execute build
        run: ./gradlew build