# https://docs.github.com/en/actions/learn-github-actions/contexts
# https://docs.github.com/en/actions/learn-github-actions/expressions

name: Information workflow
on: workflow_dispatch
jobs:
  information:
    runs-on: ubuntu-latest
    steps:
      - name: Print meta-info/context - (github context here) passed into these jobs/steps
        run: echo "${{ toJSON(github) }}"